# -*- coding: utf-8 -*-
"""Loops in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10W66VYOKxq9-6XkD964-6stE1wwfiXVC

#For loop
"""

laptop1 = int(input('Enter the price of the laptop : '))
laptop2 = int(input('Enter the price of the laptop : '))
laptop3 = int(input('Enter the price of the laptop : '))
laptop4 = int(input('Enter the price of the laptop : '))
laptop5 = int(input('Enter the price of the laptop : '))

for i in range(5):
  laptop_price = int(input('Enter the price of the laptop : '))

numbers = [50, 100, 150, 200]
print(numbers[0])
print(numbers[1])
print(numbers[2])
print(numbers[3])

numbers = [50, 100, 150, 200]
for i in numbers:
  print(i)

"""#While loop

while condition:
    statement
"""

i = 0
while i < 10:
  print(i)
  i += 1

i = 5
while i < 3:
  print(i)
  i += 1