# -*- coding: utf-8 -*-
"""Where to collect Data for Machine Learning.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fTPJqHZv3mCbCWtLP-Oj8Q1lw4f2fRb8

#Data Collection Sites


1.   Kaggle
2.   UCI Machine Learning Repository
3.   Google Dataset Search
"""

import pandas as pd

# loading a dataset to a pandas dataframe
dataset = pd.read_csv('/content/housing.csv')

dataset.head()