# -*- coding: utf-8 -*-
"""Handling Missing Values.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CeAS67HZOQkUJuGGog_M4gCjl4D7P-XA

#Methode to Handle Missing Values
1.   Imputation
2.   Dropping

#Importing the libraries
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# loading the dataset to a Pandas DataFrame
dataset = pd.read_csv('/content/Placement_Dataset.csv')

dataset.head()

dataset.shape

dataset.isnull().sum()

"""#Imputation

#Central Tendencies
1.   Mean (average)
2.   Median (central)
3.   Mode (more repeated)
"""

# analyse the distribution of data in the salary
fig, ax = plt.subplots(figsize=(8,8))
sns.distplot(dataset.salary)

"""#Replace the missing values with Median value"""

dataset['salary'].fillna(dataset['salary'].median(), inplace=True)

dataset.isnull().sum()

# filling missing value with Mean value
# dataset['salary'].fillna(dataset['salary'].mean(), inplace=True)

# filling missing value with Mode value
# dataset['salary'].fillna(dataset['salary'].mode(), inplace=True)

"""#Dropping Method"""

salary_dataset = pd.read_csv('/content/Placement_Dataset.csv')

salary_dataset.shape

salary_dataset.isnull().sum()

# drop the missing values
salary_dataset = salary_dataset.dropna(how='any')

salary_dataset.isnull().sum()

salary_dataset.shape