# -*- coding: utf-8 -*-
"""Label Encoding.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tvDvnEoqTmVSnC7oRovi8WoF87ikDjO6

#Label Encoding
*   converting the labels into numeric form
"""

# importing the Dependencies
import pandas as pd
from sklearn.preprocessing import LabelEncoder

"""#Label Encoding of Breast Cancer Dataset"""

# loading the datafrom csv file to pandas dataframe
cancer_data = pd.read_csv('/content/data.csv')

# first 5 row of the dataframe
cancer_data.head()

# finding the count of different labels
cancer_data['diagnosis'].value_counts()

# load the Label Encoder function
label_encode = LabelEncoder()

labels = label_encode.fit_transform(cancer_data.diagnosis)

# appending the labels to the dataframe
cancer_data['target'] = labels

cancer_data.head()

"""0 --> Benign
1 --> Malignant
"""

cancer_data['target'].value_counts()

"""#Label Encoding of iris data"""

# loading the datafrom csv file to pandas dataframe
iris_data = pd.read_csv('/content/iris_data.csv')

# first 5 row of the dataframe
iris_data.head()

# finding the count of different labels
iris_data['Species'].value_counts()

# load the Label Encoder function
label_encode_iris = LabelEncoder()

labels = label_encode_iris.fit_transform(iris_data.Species)

# appending the labels to the dataframe
iris_data['target'] = labels

iris_data.head()

"""Iris-setosa --> 0
Iris-versicolor --> 1
Iris-virginica --> 2
"""

iris_data['target'].value_counts()