# -*- coding: utf-8 -*-
"""5.1.9_Matrix_Operations_in_Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qW3qAcdu8WY3Wlg76L6imFdMrAx9KUGT

#Importing Numpy Library
"""

import numpy as np

"""#Matrix Addition
Two matrices can be added only if they have the same shape
"""

# creating two matrices
A = np.array([[2,3],[10,5]])
B = np.array([[10,5],[20,4]])

print(A)

print(B)

A.shape

B.shape

"""#Adding two Matrices"""

sum = A + B

print(sum)

# create two matrices with random values
matrix_1 = np.random.randint(10, size=(3,3))
matrix_2 = np.random.randint(20, size=(3,3))

print(matrix_1)

print(matrix_2)

sum = np.add(matrix_1, matrix_2)

print(sum)

# create two matrices with random values
matrix_3 = np.random.randint(10, size=(3,3))
matrix_4 = np.random.randint(20, size=(3,4))

# sum_2 = np.add(matrix_3,matrix_4)
# we get error because shape of matrix_3 and matrix_4 are different

"""#Martix Subtraction"""

diff = A - B

print(diff)

diff = np.subtract(matrix_1, matrix_2)

print(diff)

# diff_2 = np.subtract(matrix_3,matrix_4)
# we get error because shape of matrix_3 and matrix_4 are different

"""#Multiplying a Martix by Scalar"""

x = 5
y = np.array([[2,1],[4,2],[6,3]])

print(y)

product = x * y

print(product)

w = 10
z = np.random.randint(10, size=(4,4))

print(z)

product = np.multiply(w, z)

print(product)

"""#Multiplying 2 Martices"""

E = np.array([[2,3],[8,6]])
F = np.array([[10,5],[20,4]])

print(E)

print(F)

product = np.dot(E, F)
product2 = E * F

print(product)

print(product2)

"""np.dot is different than *"""

# create two matrices with random values
matrix_5 = np.random.randint(5, size=(3,3))
matrix_6 = np.random.randint(5, size=(3,4))

print(matrix_5)

print(matrix_6)

product = np.dot(matrix_5, matrix_6)

print(product)

# create two matrices with random values
matrix_7 = np.random.randint(5, size=(3,3))
matrix_8 = np.random.randint(5, size=(4,4))

# product = np.dot(matrix_7, matrix_8)
# we get error because numbre of columns of matrix_7 and number of rows of matrix_8 are different

"""#Element wise matrix multiplication"""

product = np.multiply(E, F)
product2 = E * F

print(product)

print(product2)

"""np.multiply is equal than *"""

# product = np.multiply(matrix_7, matrix_8)
# we get error because shape of matrix_7 and matrix_8 are different