# -*- coding: utf-8 -*-
"""5.1.5_Vector_Operations_in_Python_Part_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Cox8spIWPnqsNPaWR7r7Dq8Z_ylmv5_
"""

import numpy as np

"""#Dot Product of 2 Vectors"""

a = np.array([2, 3])
b = np.array([4, 4])
a_dot_b = np.dot(a, b)

print(a_dot_b)

c = np.array([40, 20, 35])
d = np.array([53, 24, 68])
c_dot_d = np.dot(c, d)

print(c_dot_d)

"""#Cross Product of 2 Vectors"""

a = np.array([2, 3])
b = np.array([4, 4])
a_cross_b = np.cross(a, b)

print(a_cross_b)

c = np.array([5, 10, 20])
d = np.array([18, 32, 50])
c_cross_d = np.cross(c, d)

print(c_cross_d)

"""#Projection of 'a' Vector on 'b' Vector"""

a = np.array([2, 5])
b = np.array([8, -6])

# magnitude of "b" vector
magnitude_of_b = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b) / magnitude_of_b**2)*b
print('Projection of a vector on b vector = ', proj_of_a_on_b)

a = np.array([23, 45,62])
b = np.array([45, 82, 67])

# magnitude of "b" vector
magnitude_of_b = np.sqrt(sum(b**2))
proj_of_a_on_b = (np.dot(a,b) / magnitude_of_b**2)*b
print('Projection of a vector on b vector = ', proj_of_a_on_b)