# -*- coding: utf-8 -*-
"""Functions in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QgwxVqoqUnJwtgaKxxwYRKb5rm9hFciV

#Functions:
Function is a block of code that can be reused in a Program

#Factorial of a Number
Factorial of a number is the product of all the positive integers less than or equal to the given number
ex : Factorial of 5 = 5x4x3x2x1 = 120
"""

number = int(input(" Enter a number to find its factorial :"))
factorial = 1
if number == 0:
  print (" The Factorial of 0 is 1")
else :
  for i in range(1, number+1):
    factorial = factorial * i
  print(" The factorial of ", number, " is", factorial)

"""#Factorial Function"""

def factorial_value(num):
  factorial = 1

  if num == 0:
    return factorial
  else :
    for i in range(1, num+1):
      factorial = factorial * i
    return factorial

print(factorial_value(5))
print(factorial_value(10))