# -*- coding: utf-8 -*-
"""If Else statement in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gxkMzvkxuSf5txBpYLgOy4On7NQiBef4

#Simple if else statement
"""

# Simple if else statement
a = 30
b = 50

if (a > b) :
  print('a is the greatest number')
else:
  print('b is the greatest number')

a = int(input('Enter the first number : '))
b = int(input('Enter the second number : '))

if (a > b) :
  print('first number is the greatest')
else:
  print('second number is the greatest')

a = 15
b = 25
c = 30

if (b < a > c) :
  print('a is the greatest number')
elif (a < b > c) :
  print('b is the greatest number')
else:
  print('c is the greatest number')

"""#Nested if statement"""

a = 15
b = 25
c = 30

if (a > b) :
  if (a > c) :
    print('a is the greatest number')
  else:
    print('c is the greatest number')
else:
  if (b > c) :
    print('b is the greatest number')
  else:
    print('c is the greatest number')