# -*- coding: utf-8 -*-
"""Python Basics.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10R6rq0Tk4_WpBuqQjLlzCYYckdzCQBB3

#Print Function
"""

print('Machine Learning')

print("Machine Learning")

print('Machine Learning' + " Projetcs")

print(8)

print(8 + 3)

"""#Basics Data Types


1.   int
2.   float
3.   str
"""

type(8)

type(3.6)

type('english')

"""#Constants & Variables"""

marval_super_hero = "Iron Man"
print(marval_super_hero)

marval_super_hero = "Capitan America"
print(marval_super_hero)

hero1 , hero2 , hero3 = "Iron Man" , "Capitan America" , "Bat Man"
print(hero1)
print(hero2)
print(hero3)

x = y = z = 23
print(x)
print(y)
print(z)

"""#Input Function"""

number_1 = int(input("Enter the first number : "))
number_2 = int(input("Enter the second number : "))

sum = number_1 + number_2
print(sum)

# changing the data type in python
num = 5
print(float(num))